version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    install:
      - pip install .
      - pip install dependency-groups
      - pip-install-dependency-groups readthedocs

mkdocs:
  configuration: mkdocs.yml